version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-serverless-image-pipeline
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity 
    network_mode: host